
---
title: "Code for paper"
author: "Yimen"
date: "5/27/2020"
output: html_document
---

```{r packages, echo=FALSE, message=FALSE}
rm(list=ls())
require(arm)
require(dplyr)
require(MASS)
require(ggplot2)
require(ggpubr)
library(parallel)
require(lattice)
library(latticeExtra)
require(gridExtra)
require(pander)
require(xtable)
setwd("/home/yi/Dropbox/SocialFitnessEffects")
library(RColorBrewer)

cols=c("black", "darkgreen", "red")
alpha=0.2
```

```{r FunctionSimulate, echo=FALSE}
IBsim <- function(x){
  # initialize lists
  dAll<-list(IndData=list(), PopData=list())
  d<-list(Ind=list(), Pop=list())  # 
  dyears<-list() # a list of ind data for each year 
  
  
  #---- Among year variation ----
  # Simulate among year variation for each of n.years where
  # VYs is the among year variation in survival
  # VYr is the among year variation in reproduction
  # VYrs is the among-year covariance between survival and reproduction
  MY<-matrix(c(x$VYs, x$VYrs, x$VYrs, x$VYr),2,2)  # generate variance-covariance matrix
  Y<- as.data.frame(cbind(1:x$n.years, mvrnorm(x$n.years, c(0,0), MY)))
  colnames(Y) <- c("year", "Ys", "Yr")   # Ys/Yr are annual variation in survival and repro
  
  
  ##############################
  # Create founder population
  ##############################
  
  #---- Intrinsic values ----
  # Simulate individual intrinsic values for the founder population
  # nA is the number of adults in the founder population
  # VIr is the among individual variance in number of recruits
  # VIrs is the among individual variance in survival
  # VIrs is a pheniotype that could affect reproduction or survival
  
  # adults:
  df1<-data.frame(ID=1:(x$nA+x$nJ),                      # individual ID
                  Ir=rnorm(x$nA+x$nJ, 0, x$VIr),       # intrinsic reproductive value    
                  Is=rnorm(x$nA+x$nJ, 0, x$VIs),       # intrinsic survival value
                  z=rnorm(x$nA+x$nJ, 0, sqrt(x$Vaz)), # phenotypic trait value
                  age=c(rep(1, each=x$nA),rep(0, each=x$nJ)))                          # set age of adults to 1  
  
  # first breeding year individuals: 
  
  # Combine the adult and juvenile data into a data frame for year 1:
  d1 <- df1 %>%                   # combine adult and juvenile data 
        mutate(z_bar=mean(z),                     # calculate avg phenotype in year 1
               year=1,                            # year 
               N=nrow(.))                         # total population size in year 1
  
  
  #---- Residual values ----
  # Simulate the stochasticity that affects an individual's rep. or survival in a given year 
  MR<-matrix(c(x$VEs, x$VErs, x$VErs, x$VEr),2,2) # variance-covariance matrix
  E<-mvrnorm(nrow(d1), c(0,0), MR)
  colnames(E) <- c("Es", "Er")                    # added column names for subsetting (matches)
  

  
  #---- Model survival ----
  # calculate survival on the latent scale: 
  d1$sm <- x$s +             # average population survival 
           d1$Is +           # intrinsic survival value
           x$Bzs*(d1$z) +    # effect of phenotype on survival
           Y$Ys[1]  +        # annual variation in survival
           d1$N*x$Bns +      # density regulation
           x$as*d1$age +     # age effect
           E[,"Es"]          # residual effect
  
  d1$pr = (1/(1+exp(-d1$sm))) # transform to individual survival probabilities
  d1$surv<-rbinom(length(d1$sm),1,d1$pr) # realization for survival
  
  
  #---- Model reproduction ----
  # calculate survival on the latent scale (following same logic as survival): 
  d1$rm<- x$r + d1$Ir + x$Bzr*(d1$z) + Y$Yr[1]  + d1$N*x$Bnr + x$ar*d1$age + E[,"Er"]
 
  # the exponent of the latent trait defines the mean for the poisson process
  d1$recruits<-rpois(length(d1$rm), exp(d1$rm)) 
  
  
  #---- Calculate fitness ----
  d1$w<-d1$recruits + d1$surv  # individual fitness (the sum of survivial and no. recruits)
  d1$rw<-d1$w/mean(d1$w)       # relative fitness
  
  
  #---- Store data for year 1 ----
  # add individual data for year 1 to list dyears
  dyears[[1]]<-d1 
  
  # initialize a dataframe of population-level data for year 1
  pop <- data.frame(scenID=x$scenID,                                # scenario ID
                    year=1,                                         # year
                    N=x$nJ+x$nA,                                    # total population size
                    lambda=log(sum(d1$recruits+d1$surv)/d1$N[1]),   # growth rate 
                    z_bar=d1$z_bar[1],                              # mean phenotype (previously "z")
                    deltaz=d1$z_bar[1]+cov(d1$z, d1$rw))            # expected change in mean phenotype
  
  
  ##############################
  # Iterate over n.years
  ##############################
  

    for(i in 2:x$n.years){
      
      # Create temporary data with individuals of the previous generation 
      dtmp<-as.data.frame(dyears[[i-1]])
      
      if(sum(dtmp$surv)==0 & sum(dtmp$recruits)==0){
        break
      }  # if no individuals survive or reproduce, stop the loop 
      
      
      #---- Surviving adults ----    
      # Only the surviving adults make it to the current generation 
      dA2<-dtmp[dtmp$surv==1, c("ID", "Ir", "Is", "z")]
      dA2$age<-1 + dtmp$age[dtmp$surv==1] # increase their age
      
      #---- Create new recruits ----
      # Recruits enter the current generation, they have the same characteristics of the parents   
      Ir=rep(dtmp$Ir, dtmp$recruits)
      Is=rep(dtmp$Is, dtmp$recruits)
      z=rep(dtmp$z, dtmp$recruits)
      
      Vz<-mean((z-mean(z))^2)
      # Add intrinsic survival and reproduction merits for the new recruits 
      if (length(Ir)>0) {
        # generate unique ID for new recruits: year - parent ID - within-year ID
        dJ2<-data.frame(ID=(max(dtmp$ID)+1):(max(dtmp$ID)+sum(dtmp$recruits)))
        # calculate intrinsic value: parental value * heritability + error
        dJ2$Ir=Ir
        dJ2$Is=Is
        # calculate phenotypic value for new recruits 
        if(Vz>x$Vaz){
        dJ2$z= z 
        }else{
          dJ2$z= z + rnorm(length(z), 0, sqrt(x$Vaz-Vz))
        }
          # age of new recruits = 0
        dJ2$age<-0
      } # end recruit loop
      
      
      #---- Store individual data for the current year ---- 
      
      #--- hide these clauses for now and see if we get an error
      #--- ... see rbind() below
      # If some individuals survive and some reproduced combines the data into d2
      #if(nrow(dA2)>0 & length(Ir)>0){
      #  d2<-rbind(dA2,  dJ2)
      #}
      
      # If some individuals survive but nobody reproduced, d2 is composed by only adults of previous year 
      #if(nrow(dA2)>0 & length(Ir)==0){
      #  d2<-dA2
      #}
      # If no adult survives but some reproduce, d2 is composed of only juveniles:     
      #if(nrow(dA2)==0 & length(Ir)>0){
      #  d2<-dJ2
      #}
      
      d2 <- rbind(dA2, dJ2) %>%
        mutate(year=i, 
               N=nrow(.)) # Population size in current year
      
  
      # Simulate stochastic variation for individual yearly survival and reproduction
      MR<-matrix(c(x$VEs, x$VErs, x$VErs, x$VEr),2,2)
      E<-matrix(mvrnorm(nrow(d2), c(0,0), MR),nrow(d2),2)
      colnames(E) <- c("Es", "Er")
      
      # Age as a categorical value and mean phenotype
      age2<-d2$age
      age2[d2$age>0]<-1
      d2$z_bar<-mean(c(dA2$z,dJ2$z))
      
      
      #---- Calculate survival and reproduction ----
      # Follows same logic as year 1, 
      # but with extra terms reflecting the interactions between population size and mean phenotype
      
      # calculate survival on the latent scale:
      d2$sm <- x$s + x$as*age2  + d2$Is + Y$Ys[i] + x$Bzs*d2$z +     d2$N*x$Bns +  E[,"Es"]
      x$BZs*d2$z_bar +             # social selection 
        x$BZns*d2$N*d2$z_bar +     # phenotype-dependent density regulation
        x$Bzns*d2$N*d2$z  +        # density-dependent selection
        x$BZzs*d2$z*d2$z_bar +     # frequency-dependent selection
        x$BZzns*d2$z*d2$z_bar*d2$N # link between density- and frequency-dependent selection
      
      # probability of survival: 
      d2$pr = (1/(1+exp(-d2$sm))) 
      
      # realized survivial: 
      d2$surv<-rbinom(length(d2$sm),1,d2$pr) # realization
      
      # calculcate reproduction on the latent scale
      d2$rm <- x$r + x$ar*age2 +  d2$Ir + Y$Yr[i] + x$Bzr*d2$z + 
        x$Bzr2*d2$z^2 + d2$N*x$Bnr + E[,"Er"] + 
        x$BZr*d2$z_bar + 
        x$BZnr*d2$N*d2$z_bar + 
        x$Bznr*d2$N*d2$z  + 
        x$BZzr*d2$z*d2$z_bar+ 
        x$BZznr*d2$z*d2$z_bar*d2$N  
     
       # realized reproduction
      d2$recruits<-rpois(length(d2$rm), exp(d2$rm)) 
      
      # calculate fitness 
      d2$w<-d2$recruits + d2$surv    
      d2$rw<-d2$w/mean(d2$w)
      
      # add individual data for year i to list dyears 
      dyears[[i]]<-d2
      
      # add population-level data for current year to pop dataframe 
      pop <- pop %>% 
        add_row(scenID=x$scenID,                                  # scenario ID
                year=i,                                           # year
                N=sum(dtmp$recruits + dtmp$surv),                 # total population size
                z_bar=d2$z_bar[1],                                # mean phenotype (previously "z")
                lambda=log(sum(d2$recruits + d2$surv)/d2$N[1]),   # growth rate
                deltaz=mean(d2$z)+cov(d2$z, d2$rw))               # expected change in mean phenotype
    } # end loop

  
  #---- Format data ----
  dtmp1<-do.call(rbind.data.frame, dyears)  # combine ind. data for all years into a dataframe 
  dtmp1$simID<- x$sim                         # simulation ID
  dtmp1$scenID<- x$scenID 
  pop$simID <- x$sim                          # column for simulationID
  pop$scenID <- x$scenID
  # column for simulation 
  
  dAll$IndData<-dtmp1                       # add yearly data to a list
  dAll$PopData<-pop                         # add population data to a list
  dAll$Param<-x
  dAll
  }
```

```{r FunctionSimPops, echo=FALSE}

sim.pops <- function(x, n.sims, n.Cores=detectCores()-1, seed=FALSE){  
  lists<-list()  # initialize list of parameter values for each scenario
  for(j in 1:n.sims){
    lists[[j]]<- cbind(x, sim=j)  # create list of paramter values (all same) and simulation ID (unique)
  }    
  
  res <- mclapply(lists, IBsim, mc.cores=n.Cores, mc.set.seed=seed) 
  res
  }

make.dataframe<-function(x){
  d<- list()
  d$Ind<-do.call(rbind.data.frame, lapply(x, '[[', 1))
  d$Pop<-do.call(rbind.data.frame, lapply(x, '[[', 2)) 
  d$Params<-as.data.frame(x$params)
  d
  
}

```

```{r FunctionCreateX, echo=FALSE}
# A function to calculate x. Function contains default values so that it is clear what is changing in each scenario. 
# scenID is scenario ID
# n.years is the number of years per simulation
create.x <- function(scenID, n.years=200, s=-0.1, r=0.1, Bns=0, Bnr=-0.01, nJ=10, nA=10,ar=0, as=0, h2r=0, h2s=0, h2rs=1, VYs=0, VYr=0, VYrs=0, VIr=0, VIs=0,  Vaz=1, VEs=0, VEr=0, VErs=0, Bzr=0, Bzr2=0, Bzs=0, BZr=0, BZs=0, BZnr=0, BZns=0, Bznr=0, Bzns=0, BZzr=0,  BZzs=0, BZznr=0,  BZzns=0){
  data.frame(scenID=scenID, n.years=n.years, s=s, r=r, Bns=Bns, Bnr=Bnr, nJ=nJ, nA=nA,
             ar=ar, as=as, h2r=h2r, h2s=h2s, h2rs=h2rs,
             VYs=VYs, VYr=VYr, VYrs=VYrs, VIs=VIs, VIr=VIr, Vaz=Vaz, VEs=VEs, VEr=VEr, 
             VErs=VErs, Bzr=Bzr, Bzr2=Bzr2, Bzs=Bzs, BZr=BZr, BZs=BZs, BZnr=BZnr, BZns=BZns,
             Bznr=Bznr, Bzns=Bzns, BZzr=BZzr, BZzs=BZzs, BZznr=BZznr, BZzns=BZzns)
}
```

```{r FunctionCalcSimAvg, echo=FALSE}
# this function combines functions Nbar() and zbar()
# accepts as arguments the output of sim.pops for three scenarios (a, b,c) and calculates the avg yearly population size and phenotype accross all simulations in each scenario
calc.simAvg <- function(a, b, c){
    rbind(a$Pop, b$Pop, c$Pop) %>%                # combine data from all scenarios
    group_by(scenID, year) %>%                    # for each year in each scenario, calculate... 
    summarize(Nbar = mean(N, na.rm=TRUE),         # mean population size 
              zbar = mean(z_bar, na.rm=TRUE),     # mean phenotype
              sigma2z = var(z_bar, na.rm=TRUE)) 
}

calc.YearlySigma <- function(a, b, c){
    rbind(a$Ind, b$Ind, c$Ind) %>%                # combine data from all scenarios
    group_by(scenID, year) %>%                    # for each year in each scenario, calculate... 
    summarize(sigma2z = var(z_bar, na.rm=TRUE)) 
}


```

```{r FunctionExtinction, echo=FALSE}
# a function to calculate extinction (replaces Ext())
calc.ext <- function(a, b, c){
    rbind(a$Pop, b$Pop, c$Pop) %>%
    group_by(scenID, sim) %>% 
    summarize(max.year=max(year), .group='keep') %>%
    mutate(prop.ext=sum(max.year<100)/max(sim)) %>%
    group_by(scenID) %>% summarize(ext=mean(prop.ext), )
}
```

```{r FunctionAnalyze, echo=FALSE}
model.1<-function(x){
mod<-lm(w~N, data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]

EN=as.vector(-(B1-1)/Bn)

res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]), EN=EN, Ez=NA, B1, Bn)
res$biasN=as.vector(res$EN-res$N)
res$scenID=x$scenID[1]
res
}

model.2<-function(x){
x$z2<-x$z^2
mod<-lm(w~N + z + z2, data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
zp=(-Bl/(2*Bq))
EN=as.vector(-(B1 + Bl*zp + Bq*zp^2+Bq*var(x$z[x$year==max(x$year)])-1)/Bn)

res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]), EN=EN, Ez=zp, B1, Bn, Bl, Bq)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

model.3<-function(x){
x$z2<-x$z^2
mod<-lm(w~N + z + z2 +  z_bar , data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
Bz=coef(mod)[5]
zp=(-Bl/(2*Bq))

EN=(-1 + B1 + Bl*zp + Bz*zp+  Bq*zp^2  + Bq*var(x$z[x$year==max(x$year)]))/-(Bn)

res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]),  EN=EN, Ez=zp, B1, Bn, Bl, Bq, Bz)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

model.4<-function(x){
x$z2<-x$z^2
mod<-lm(w~ N + z + z2 + z_bar + z_bar:N , data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
Bz=coef(mod)[5]
Bnz=coef(mod)[6]
zp=(-Bl/(2*Bq))

EN=(-1 + B1 + Bl*zp + Bz*zp+  Bq*zp^2  + Bq*var(x$z[x$year==max(x$year)]))/-(Bn + Bnz*zp)


res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]),  EN=EN, Ez=zp, B1, Bn, Bl, Bq, Bz, Bnz)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

model.5<-function(x){
x$z2<-x$z^2
mod<-lm(w~ N + z + z2 + z:N  , data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
Bzn=coef(mod)[5]
N=x$N[x$year==max(x$year)][1]
s=var(x$z[x$year==max(x$year)])

zp<--(Bl - (Bl*Bzn - 2*Bn*Bq + 2*sqrt(Bq^2*Bzn^2*s + B1*Bq*Bzn^2 - Bl*Bn*Bq*Bzn + Bn^2*Bq^2 - Bq*Bzn^2))/Bzn)/(2*Bq)

EN=-(Bl*Bzn - 2*Bn*Bq + 2*sqrt(Bq^2*Bzn^2*s + B1*Bq*Bzn^2 - Bl*Bn*Bq*Bzn + Bn^2*Bq^2 - Bq*Bzn^2))/Bzn^2

res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]),  EN=EN, Ez=zp, B1, Bn, Bl, Bq, Bzn)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

model.6<-function(x){
x$z2<-x$z^2
mod<-lm(w~ N + z + z2 + z_bar + z:z_bar  , data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
Bz=coef(mod)[5]
Bzz=coef(mod)[6]
zp<--(Bl)/(2*Bq + Bzz)

EN=(-1 + B1 + (Bl + Bz)*zp  +  (Bzz + Bq)*zp^2 + Bq*var(x$z[x$year==max(x$year)]))/-Bn

res<-data.frame(N=x$N[x$year==max(x$year)][1], z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]),  EN=EN, Ez=zp, B1, Bn, Bl, Bq, Bz, Bzz)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

model.7<-function(x){
x$z2<-x$z^2
mod<-lm(w~ N + z + z2 + z_bar + z_bar:N + z:N + z_bar:z + z_bar:N:z, data=x)
B1=coef(mod)[1]
Bn=coef(mod)[2]
Bl=coef(mod)[3]
Bq=coef(mod)[4]
Bz=coef(mod)[5]
BNZ=coef(mod)[6]
BNz=coef(mod)[7]
BZz=coef(mod)[8]
BNZz=coef(mod)[9]

N=x$N[x$year==max(x$year)][1]

zp<--(Bl + BNz*N)/(2*Bq + BZz + BNZz*N)

EN=(-1 + B1 + (Bl + Bz)*zp  +  (BZz + Bq)*zp^2 + Bq*var(x$z[x$year==max(x$year)]))/-(Bn + BNz*zp + BNZz*zp^2 + BNZ*zp) 

res<-data.frame(EN=EN, N=N, Ez=zp, z=mean(x$z[x$year==max(x$year)]), Vz=var(x$z[x$year==max(x$year)]),B1, Bn, Bl, Bq, Bz, BNZ, BNz, BZz, BNZz)
res$scenID=x$scenID[1]
res$biasN=as.vector(res$EN-res$N)
res
}

analyze<-function(x,y,z, model){
an1<-do.call(rbind.data.frame,mclapply(lapply(x, '[[', 1), model, mc.cores=3))
an2<-do.call(rbind.data.frame,mclapply(lapply(y, '[[', 1), model, mc.cores=3))
an3<-do.call(rbind.data.frame,mclapply(lapply(z, '[[', 1), model, mc.cores=3))
b<-rbind(an1,an2,an3)
}
```

```{r FunctionsPredict, echo=FALSE}

predict1<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n
w2=x$B1[2] + x$Bn[2]*n
w3=x$B1[3] + x$Bn[3]*n
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}


predict2<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1]
w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2]
w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3]
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}

predict3<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*x$Ez[1]
w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*x$Ez[2]
w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*x$Ez[3]
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}

predict4<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*x$Ez[1] + x$Bnz[1]*x$Ez[1]*n
w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*x$Ez[2] + x$Bnz[2]*x$Ez[2]*n
w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*x$Ez[3]  + x$Bnz[3]*x$Ez[3]*n
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}

predict5<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*x$Ez[1] + x$Bzn[1]*n*x$Ez[1]

w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*x$Ez[2] + x$Bzn[2]*n*x$Ez[2]


w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*x$Ez[3] + x$Bzn[3]*n*x$Ez[3]
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}

predict6<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  
w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*x$Ez[1] +  x$Bzz[1]*x$Ez[1]^2
w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*x$Ez[2] + x$Bzz[2]*x$Ez[2]^2
w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*x$Ez[3]  + x$Bzz[3]*x$Ez[3]^2
res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}


predict7<-function(x, y){
x<-as.data.frame(x)
n<-seq(1:y)  

w1=x$B1[1] + x$Bn[1]*n + x$Bl[1]*x$Ez[1] + x$Bq[1]*x$Ez[1]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*x$Ez[1] +  x$BNZ[1]*x$Ez[1]*n + x$BNz[1]*x$Ez[1]*n + x$BZz[1]*x$Ez[1]^2 + x$BNZz[1]*x$Ez[1]^2*n

w2=x$B1[2] + x$Bn[2]*n + x$Bl[2]*x$Ez[2] + x$Bq[2]*x$Ez[2]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*x$Ez[2] +  x$BNZ[2]*x$Ez[2]*n + x$BNz[2]*x$Ez[2]*n + x$BZz[2]*x$Ez[2]^2 + x$BNZz[2]*x$Ez[2]^2*n

w3=x$B1[3] + x$Bn[3]*n + x$Bl[3]*x$Ez[3] + x$Bq[3]*x$Ez[3]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*x$Ez[3] +  x$BNZ[3]*x$Ez[3]*n + x$BNz[3]*x$Ez[3]*n + x$BZz[3]*x$Ez[3]^2 + x$BNZz[3]*x$Ez[3]^2*n

res<-data.frame(w=c(w1,w2,w3),n, scenID=rep(x$scenID, each=y))
res
}


popdyn1<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10

r<-x$B1
for(i in 1:(y-1)){
  w[i,]<-r + x$Bn*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID,each=y)))
res}


popdyn2<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10

r<-x$B1 + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz
for(i in 1:(y-1)){
  w[i,]<-r + x$Bn*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID,each=y)))
res

}

popdyn3<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10
r<-x$B1 + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz + x$Bz*x$Ez
for(i in 1:(y-1)){
  w[i,]<-r + x$Bn*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID,each=y)))
res
}

popdyn4<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10
r<-x$B1 + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz + x$Bz*x$Ez

for(i in 1:(y-1)){
  w[i,]<-r + (x$Bn + x$Bnz*x$Ez)*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID, each=y)))
}

popdyn5<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10
r<-x$B1 + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz + x$Bz*x$Ez

for(i in 1:(y-1)){
  w[i,]<-r +  (x$Bn + x$Bzn*x$Ez)*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID, each=y)))
res
 }

popdyn6<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10
r<-x$B1 + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz +  x$Bz*x$Ez + x$Bzz*x$Ez^2
for(i in 1:(y-1)){
  w[i,]<-r +  (x$Bn)*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID, each=y)))
res
 }

popdyn7<-function(x,y){
x<-as.data.frame(x)
dndt<-w<-N<-matrix(NA,y,3)
dndt3<-dndt2<-dndt<-w<-N<-N2<-N3<-matrix(NA,y,3)
N3[1,]<-N2[1,]<-N[1,]<-10
r<-x$B1  + x$Bl*x$Ez + x$Bq*x$Ez^2 + x$Bq*x$Vz +  x$Bz*x$Ez +   + x$BZz*x$Ez^2 
for(i in 1:(y-1)){
  w[i,]<-r +  (x$Bn+x$BNZ*x$Ez+x$BNz*x$Ez+x$BNZz*x$Ez^2)*N[i,]
  N[i+1,]<-N[i,]*w[i,]
  dndt[i,]<-N[i+1,]-N[i,]
  dndt2[i,]<-N2[i,]*log(r)*(1-(N2[i,]/x$EN))
  N2[i+1,]<-N2[i,]+dndt2[i,]
  dndt3[i,]<-N3[i,]*log(r)*(1-(N3[i,]/x$EN)^1.51)
  N3[i+1,]<-N3[i,]+dndt3[i,]
}

res<-data.frame(N=matrix(N,y*3), N2=matrix(N2,y*3), N3=matrix(N3,y*3),w=matrix(w,y*3), dndt=matrix(dndt,y*3), year=1:y, scenID=as.factor(rep(x$scenID, each=y)))
res
 }



```

# Scenario 1: Density regulation
```{r S1_densityRegulation, cache=TRUE}

n.sims = 200
#seed <- 705

# scenarios to simulate (uses base parameters in create.x() and varies Bnr...)
s1a.x <- create.x(scenID="1a",  Bnr=-0.01)
s1b.x <- create.x(scenID="1b",  Bnr=-0.02)
s1c.x <- create.x(scenID="1c",  Bnr=-0.03)

# run simulations in three scenarios (vary Bnr)
s1a <- sim.pops(n.sims=n.sims, x=s1a.x)  
s1b <- sim.pops(n.sims=n.sims, x=s1b.x)
s1c <- sim.pops(n.sims=n.sims, x=s1c.x)


ds1a<-make.dataframe(s1a) 
ds1b<-make.dataframe(s1b)
ds1c<-make.dataframe(s1c)
df1 <- calc.simAvg(ds1a, ds1b, ds1c)

an1<-analyze(s1a, s1b, s1c, model.1)

est1<-an1 %>%  group_by(scenID) %>% summarise_all(mean)  

pred1<-predict1(est1, 200)

```

```{r, DensityRegulationFigure3, echo=FALSE}
p1.n <- ggplot(df1, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="A) Density regulation", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_hline(data=est1, aes(yintercept = EN), colour=cols, linetype="dashed") 
  
p1.z <- ggplot(df1, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) +   theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + ylim(-4,4)

p1.w <- ggplot(pred1, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + xlim(0,100)+ labs(title="", x="N", y = expression(bar(w)))  + theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("1a", "1b", "1c"),
labels=c(bquote(paste("b"["n"], "=", .(s1a.x$Bnr))),bquote(paste("b"["n"], "=", .(s1b.x$Bnr))),bquote(paste("b"["n"], "=", .(s1c.x$Bnr)))))

ggarrange(p1.n, p1.z, p1.w,ncol=3, nrow=1) 
```

```{r, DensityRegulationFigureS1, echo=FALSE}
pd1<-popdyn1(est1, 25)

ppd1<-ggplot(pd1, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd1, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd1, aes(x = year, y = N3, color=scenID),show.legend = FALSE)



ppd2<-ggplot(pd1, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd1, ppd2, ncol=2, nrow=1) 
```

```{r, DensityRegulationFigureS, echo=FALSE}

par(mfrow=c(3,3))
hist(ds1a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds1b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds1c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds1a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds1b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds1c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds1a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds1b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds1c$Pop$N, freq=FALSE, xlab="Population size", main="")
```




# Scenario 2: Selection
```{r S2_Selection, cache=TRUE}

n.sims = 200

s2a.x <- create.x(scenID="2a",  Bnr=-0.02, Bzr= 0.00, Bzr2= 0.00)
s2b.x <- create.x(scenID="2b",  Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02)
s2c.x <- create.x(scenID="2c",  Bnr=-0.02, Bzr= 0.20, Bzr2=-0.02)

s2a <- sim.pops(n.sims=n.sims, x=s2a.x)  
s2b <- sim.pops(n.sims=n.sims, x=s2b.x)
s2c <- sim.pops(n.sims=n.sims, x=s2c.x)

ds2a<-make.dataframe(s2a) 
ds2b<-make.dataframe(s2b)
ds2c<-make.dataframe(s2c)
df2 <- calc.simAvg(ds2a, ds2b, ds2c)

an2<-analyze(s2a, s2b, s2c, model.2)

est2<-an2 %>%  group_by(scenID) %>% summarise_all(mean)  

pred2<-predict2(est2, 300)

```

```{r, SelectionFigure3, echo=FALSE}
p2.n <- ggplot(df2, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="B) Selection", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +  geom_hline(data=est2, aes(yintercept = EN), colour=cols, linetype="dashed") 

p2.z <- ggplot(df2, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est2, aes(yintercept = Ez), colour=cols, linetype="dashed") 

p2.w <- ggplot(pred2, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("2a", "2b", "2c"),
labels=c(bquote(paste("b"["z"], "=", .(s2a.x$Bzr))),bquote(paste("b"["z"], "=", .(s2b.x$Bzr))),bquote(paste("b"["z"], "=", .(s2c.x$Bzr)))))

ggarrange(p2.n, p2.z, p2.w,ncol=3, nrow=1) 
```

```{r, SelectionFigureS1, echo=FALSE}
pd2<-popdyn1(est2, 25)

ppd2a<-ggplot(pd2, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd2, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd2, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd2b<-ggplot(pd2, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd2a, ppd2b, ncol=2, nrow=1) 
```

```{r, SelectionFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds2a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds2b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds2c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds2a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds2b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds2c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds2a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds2b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds2c$Pop$N, freq=FALSE, xlab="Population size", main="")
```



# Scenario 3: Social selection
```{r S3_SocialSelection, cache=TRUE}

n.sims = 200

s3a.x <- create.x(scenID="3a", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.00)
s3b.x <- create.x(scenID="3b", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr= 0.06)
s3c.x <- create.x(scenID="3c", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.06)

s3a <- sim.pops(n.sims=n.sims, x=s3a.x)  
s3b <- sim.pops(n.sims=n.sims, x=s3b.x)
s3c <- sim.pops(n.sims=n.sims, x=s3c.x)

ds3a<-make.dataframe(s3a) 
ds3b<-make.dataframe(s3b)
ds3c<-make.dataframe(s3c)
df3 <- calc.simAvg(ds3a, ds3b, ds3c)

an3<-analyze(s3a, s3b, s3c, model.3)

est3<-an3 %>%  group_by(scenID) %>% summarise_all(mean)  

pred3<-predict3(est3, 300)

```

```{r, SocialSelectionFigure3, echo=FALSE}
p3.n <- ggplot(df3, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="C) Social selection", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +  geom_hline(data=est3, aes(yintercept = EN), colour=cols, linetype="dashed") 

p3.z <- ggplot(df3, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est3, aes(yintercept = Ez), colour=cols, linetype="dashed") 

z<-s3a.x$BZr

p3.w <- ggplot(pred3, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("3a", "3b", "3c"),
labels=c( bquote(paste("b"[bar(z)], "=", .(s3a.x$BZr))), bquote(paste("b"[bar(z)], "=", .(s3b.x$BZr))),bquote(paste("b"[bar(z)], "=", .(s3c.x$BZr)))))

ggarrange(p3.n, p3.z, p3.w,ncol=3, nrow=1) 
```

```{r, SocialSelectionFigureS1, echo=FALSE}
pd3<-popdyn3(est3, 25)

ppd3a<-ggplot(pd3, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd3, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd3, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd3b<-ggplot(pd3, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd3a, ppd3b, ncol=2, nrow=1) 
```

```{r, SocialSelectionFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds3a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds3b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds3c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds3a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds3b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds3c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds3a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds3b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds3c$Pop$N, freq=FALSE, xlab="Population size", main="")

```



# Scenario 4: Phenotype Dependent Density Regulation
```{r S4_PhenotypeDependentDensityRegulation, cache=TRUE}

n.sims = 200

s4a.x <- create.x(scenID="4a", n.years=200, Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=-0.03, BZnr = 0.00)

s4b.x <- create.x(scenID="4b", n.years=200, Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=-0.03, BZnr = -0.001)

s4c.x <- create.x(scenID="4c", n.years=200, Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=-0.03, BZnr = -0.002)

s4a <- sim.pops(n.sims=n.sims, x=s4a.x)  
s4b <- sim.pops(n.sims=n.sims, x=s4b.x)
s4c <- sim.pops(n.sims=n.sims, x=s4c.x)

ds4a<-make.dataframe(s4a) 
ds4b<-make.dataframe(s4b)
ds4c<-make.dataframe(s4c)
df4 <- calc.simAvg(ds4a, ds4b, ds4c)

an4<-analyze(s4a, s4b, s4c, model.4)

est4<-an4 %>%  group_by(scenID) %>% summarise_all(mean)  

pred4<-predict4(est4, 300)

```

```{r, PhenotypeDependentDensityRegulationFigure3, echo=FALSE}
p4.n <- ggplot(df4, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="D) Phenotype-dep. density regulation", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5))  +   geom_hline(data=est4, aes(yintercept = EN), colour=cols, linetype="dashed") 

p4.z <- ggplot(df4, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est4, aes(yintercept = Ez), colour=cols, linetype="dashed") 

z<-s4a.x$BZr

p4.w <- ggplot(pred4, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("4a", "4b", "4c"),
labels=c( bquote(paste("b"[paste(N,bar(z))], "=", .(s4a.x$BZnr))), bquote(paste("b"[paste(N,bar(z))], "=", .(s4b.x$BZnr))),bquote(paste("b"[paste(N,bar(z))], "=", .(s4c.x$BZnr)))))

ggarrange(p4.n, p4.z, p4.w,ncol=3, nrow=1) 
```

```{r, PhenotypeDependentDensityRegulationFigureS1, echo=FALSE}
pd4<-popdyn1(est4, 25)

ppd4a<-ggplot(pd4, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd4, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd4, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd4b<-ggplot(pd4, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd4a, ppd4b, ncol=2, nrow=1) 
```

```{r, PhenotypeDependentDensityRegulationFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds4a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds4b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds4c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds4a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds4b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds4c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds4a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds4b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds4c$Pop$N, freq=FALSE, xlab="Population size", main="")

```



# Scenario 5: Density Dependent selection
```{r S5_DensityDependentSelection, cache=TRUE}

n.sims = 200
#seed <- 705

s5a.x <- create.x(scenID="5a",  Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=0.00, Bznr = 0.00)

s5b.x <- create.x(scenID="5b", Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=0.00, Bznr = -0.001)

s5c.x <- create.x(scenID="5c", Bnr=-0.02, Bzr= 0.15, 
                  Bzr2=-0.02, BZr=0.00, Bznr = -0.003)

# run simulations in three scenarios 
s5a <- sim.pops(n.sims=n.sims, x=s5a.x)  
s5b <- sim.pops(n.sims=n.sims, x=s5b.x)
s5c <- sim.pops(n.sims=n.sims, x=s5c.x)

ds5a<-make.dataframe(s5a) 
ds5b<-make.dataframe(s5b)
ds5c<-make.dataframe(s5c)
df5 <- calc.simAvg(ds5a, ds5b, ds5c)

an5<-analyze(s5a, s5b, s5c, model.5)

est5<-an5 %>%  group_by(scenID) %>% summarise_all(mean)  

pred5<-predict5(est5, 300)

```

```{r, DensityDependentSelectionFigure4, echo=FALSE}
p5.n <- ggplot(df5, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="A) Density-dep selection", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5))  +   geom_hline(data=est5, aes(yintercept = EN), colour=cols, linetype="dashed") 

p5.z <- ggplot(df5, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) +
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est5, aes(yintercept = Ez), colour=cols, linetype="dashed") 

z<-s4a.x$BZr

p5.w <- ggplot(pred5, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("5a", "5b", "5c"),
labels=c( bquote(paste("b"[Nz], "=", .(s5a.x$Bznr))), bquote(paste("b"[Nz], "=", .(s5b.x$Bznr))),bquote(paste("b"[Nz], "=", .(s5c.x$Bznr)))))

ggarrange(p5.n, p5.z, p5.w,ncol=3, nrow=1) 
```

```{r, DensityDependentSelectionFigure5, echo=FALSE}

x<-as.data.frame(est5)
n<-seq(1,50)  
z<-seq(-2,2, by=0.1)
zz<-expand.grid(n,z)
colnames(zz)<-c("n", "z")

w1=x$B1[1] + x$Bn[1]*x$EN[1] + x$Bq[1]*x$Vz[1] +  (x$Bl[1] + x$Bzn[1]*zz[,"n"])*zz[,"z"] + x$Bq[1]*zz[,"z"]^2
rw<-w1/mean(w1)

p3d1<-cloud(rw~zz[,"n"]*zz[,"z"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(0.6,1.4),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="(A)")

w2=x$B1[2] + x$Bn[2]*x$EN[2] + x$Bq[2]*x$Vz[2] + (x$Bl[2] + x$Bzn[2]*zz[,"n"])*zz[,"z"] + x$Bq[2]*zz[,"z"]^2
rw<-w1/mean(w1)

p3d2<-cloud(w2~zz[,"n"]*zz[,"z"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(0.6,1.4),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")


w3=x$B1[3] + x$Bn[3]*x$EN[2] + x$Bq[3]*x$Vz[3] + (x$Bl[3] + x$Bzn[3]*zz[,"n"])*zz[,"z"] + x$Bq[3]*zz[,"z"]^2

p3d3<-cloud(w3~zz[,"n"]*zz[,"z"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(0.6,1.4),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")


grid.arrange(p3d1,p3d2,p3d3, ncol=3, nrow=1)
dev.off()


```

```{r, DensityDependentSelectionFigureS1, echo=FALSE}
pd5<-popdyn5(est5, 25)

ppd5a<-ggplot(pd5, aes(x = year, y = N, color=scenID)) +  
  geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + 
  theme_classic()  + labs(title="A)", x="Year", y = "N")  +
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + 
  geom_line(data=pd5, aes(x = year, y = N2, color=scenID),
  linetype="dashed",show.legend = FALSE)+ geom_line(data=pd5, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd5b<-ggplot(pd5, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd5a, ppd5b, ncol=2, nrow=1) 
```

```{r, DensityDependentSelectionFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds5a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds5b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds5c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds5a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds5b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds5c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds5a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds5b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds5c$Pop$N, freq=FALSE, xlab="Population size", main="")

```



# Scenario 6: Frequency dependent selection
```{r S6_FrequencyDependentSelection, cache=TRUE}

n.sims = 200
#seed <- 705

s6a.x <- create.x(scenID="6a", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZzr= 0.0)
s6b.x <- create.x(scenID="6b", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZzr=-0.005)
s6c.x <- create.x(scenID="6c", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZzr=-0.001)

s6a <- sim.pops(n.sims=n.sims, x=s6a.x)  
s6b <- sim.pops(n.sims=n.sims, x=s6b.x)
s6c <- sim.pops(n.sims=n.sims, x=s6c.x)

ds6a<-make.dataframe(s6a) 
ds6b<-make.dataframe(s6b)
ds6c<-make.dataframe(s6c)
df6 <- calc.simAvg(ds6a, ds6b, ds6c)

an6<-analyze(s6a, s6b, s6c, model.6)

est6<-an6 %>%  group_by(scenID) %>% summarise_all(mean)  

pred6<-predict6(est6, 300)

```

```{r, FrequencyDependentSelectionFigure4, echo=FALSE}
p6.n <- ggplot(df6, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="B) Frequency-dep selection", x="Year", y = "N") + ylim(0,100) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +  geom_hline(data=est6, aes(yintercept = EN), colour=cols, linetype="dashed") 

p6.z <- ggplot(df6, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est6, aes(yintercept = Ez), colour=cols, linetype="dashed") 

p6.w <- ggplot(pred6, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("6a", "6b", "6c"),
labels=c( bquote(paste("b"[paste(bar(z),z)], "=", .(s6a.x$BZzr))), bquote(paste("b"[paste(bar(z),z)], "=", .(s6b.x$BZzr))),bquote(paste("b"[paste(bar(z),z)], "=", .(s6c.x$BZzr)))))

ggarrange(p6.n, p6.z, p6.w,ncol=3, nrow=1) 
```

```{r, FrequencyDependentSelectionFigure5, echo=FALSE}

x<-as.data.frame(est6)
z<-seq(-4, 10, by=0.2)
zz<-expand.grid(z,z)
colnames(zz)<-c("z", "z'")

w1=x$B1[1] + x$Bn[1]*x$EN[1] + x$Bq[1]*x$Vz[1] + x$Bz[1]*zz[,"z'"] +  (x$Bl[1] + x$Bzz[1]*zz[,"z"])*zz[,"z'"] + x$Bq[1]*zz[,"z"]^2
rw<-w1/mean(w1)

p3d4<-cloud(rw~zz[,"z'"]*zz[,"z"], xlab="z'", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="(B)")

w2=x$B1[2] + x$Bn[2]*x$EN[2] + x$Bq[2]*x$Vz[2] + x$Bz[2]*zz[,"z'"] +  (x$Bl[2] + x$Bzz[2]*zz[,"z"])*zz[,"z'"] + x$Bq[2]*zz[,"z"]^2
rw<-w2/mean(w2)

p3d5<-cloud(rw~zz[,"z'"]*zz[,"z"], xlab="z'", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")


w3=x$B1[3] + x$Bn[3]*x$EN[3] + x$Bq[3]*x$Vz[3] + x$Bz[3]*zz[,"z'"] +  (x$Bl[3] + x$Bzz[3]*zz[,"z"])*zz[,"z'"] + x$Bq[3]*zz[,"z"]^2
rw<-w3/mean(w3)

p3d6<-cloud(rw~zz[,"z'"]*zz[,"z"], xlab="z'", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")

```

```{r, FrequencyDependentSelectionFigureS1, echo=FALSE}
pd3<-popdyn6(est6, 25)

ppd3a<-ggplot(pd3, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd3, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd3, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd3b<-ggplot(pd3, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd3a, ppd3b, ncol=2, nrow=1) 
```

```{r, FrequencyDependentSelectionFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds3a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds3b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds3c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds3a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds3b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds3c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds3a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds3b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds3c$Pop$N, freq=FALSE, xlab="Population size", main="")

```



# Scenario 7: Frequency-density dependent selection
```{r S6_FrequencyDensityDependentSelection, cache=TRUE}
n.sims = 200

s7a.x <- create.x(scenID="7a", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZnr= -0.001, BZznr= 0)
s7b.x <- create.x(scenID="7b", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZnr=-0.001, BZznr= -0.0003)
s7c.x <- create.x(scenID="7c", n.years=200, Bnr=-0.02, Bzr= 0.15, Bzr2=-0.02, BZr=-0.03, BZnr=-0.001, BZznr= -0.0005)

s7a <- sim.pops(n.sims=n.sims, x=s7a.x)  
s7b <- sim.pops(n.sims=n.sims, x=s7b.x)
s7c <- sim.pops(n.sims=n.sims, x=s7c.x)

ds7a<-make.dataframe(s7a) 
ds7b<-make.dataframe(s7b)
ds7c<-make.dataframe(s7c)
df7 <- calc.simAvg(ds7a, ds7b, ds7c)

an7<-analyze(s7a, s7b, s7c, model.7)

est7<-an7 %>%  group_by(scenID) %>% summarise_all(mean)  

pred7<-predict7(est7, 300)

```

```{r, FrequencyDensityDependentSelectionFigure4, echo=FALSE}
p7.n <- ggplot(df7, aes(year, Nbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="C) Density-frequency-dep selection", x="Year", y = "N") + ylim(0,50) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +  geom_hline(data=est7, aes(yintercept = EN), colour=cols, linetype="dashed") 

p7.z <- ggplot(df7, aes(year, zbar, colour=scenID)) + geom_line(show.legend = FALSE) + scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="Year", y = expression(bar(z))) + theme(axis.title.y = element_text(angle = 0, vjust=0.5)) +   geom_hline(data=est7, aes(yintercept = Ez), colour=cols, linetype="dashed") 

p7.w <- ggplot(pred7, aes(n, w, colour=scenID)) + geom_line()  + theme_classic() + ylim(0.5,2) + labs(title="", x="N", y = expression(bar(w)))  + xlim(0,100) +theme(axis.title.y = element_text(angle = 0, vjust=0.5),  legend.position = c(.95, .95), 
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6)) + scale_color_manual(values=cols, 
                       name="",
                       breaks=c("7a", "7b", "7c"),
labels=c( bquote(paste("b"[paste(bar(z),n,z)], "=", .(s7a.x$BZznr))), bquote(paste("b"[paste(bar(z),n,z)], "=", .(s7b.x$BZznr))),bquote(paste("b"[paste(bar(z),n,z)], "=", .(s7c.x$BZznr)))))

ggarrange(p7.n, p7.z, p7.w,ncol=3, nrow=1) 
```

```{r, FrequencyDensityDependentSelectionFigure5, echo=FALSE}

x<-as.data.frame(est7)
z<-seq(-4, 10, by=0.5)
n<-seq(1,50, by=2)  
zz<-expand.grid(z,z, n)
colnames(zz)<-c("z", "z'", "n")
n<-seq(1,50)  

w1=x$B1[1] + x$Bn[1]*zz[,"n"] + x$Bl[1]*zz[,"z"] + x$Bq[1]*zz[,"z"]^2 + x$Bq[1]*x$Vz[1] + x$Bz[1]*zz[,"z'"] + x$BNZ[1]*zz[,"z'"]*zz[,"n"] + x$BNz[1]*zz[,"z"]*zz[,"n"] + x$BZz[1]*zz[,"z"]*zz[,"z'"] + x$BNZz[1]*zz[,"z"]*zz[,"z'"]*zz[,"n"]
rw<-w1/mean(w1)

p3d7<-cloud(rw~zz[,"z"]*zz[,"z'"], group=zz[,"n"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="(C)")

w2=x$B1[2] + x$Bn[2]*zz[,"n"] + x$Bl[2]*zz[,"z"] + x$Bq[2]*zz[,"z"]^2 + x$Bq[2]*x$Vz[2] + x$Bz[2]*zz[,"z'"] + x$BNZ[2]*zz[,"z'"]*zz[,"n"] + x$BNz[2]*zz[,"z"]*zz[,"n"] + x$BZz[2]*zz[,"z"]*zz[,"z'"] + x$BNZz[2]*zz[,"z"]*zz[,"z'"]*zz[,"n"]
rw<-w2/mean(w2)

p3d8<-cloud(rw~zz[,"z"]*zz[,"z'"], group=zz[,"n"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")

w3=x$B1[3] + x$Bn[3]*zz[,"n"] + x$Bl[3]*zz[,"z"] + x$Bq[3]*zz[,"z"]^2 + x$Bq[3]*x$Vz[3] + x$Bz[3]*zz[,"z'"] + x$BNZ[3]*zz[,"z'"]*zz[,"n"] + x$BNz[3]*zz[,"z"]*zz[,"n"] + x$BZz[3]*zz[,"z"]*zz[,"z'"] + x$BNZz[3]*zz[,"z"]*zz[,"z'"]*zz[,"n"]
rw<-w3/mean(w3)

p3d9<-cloud(rw~zz[,"z"]*zz[,"z'"], group=zz[,"n"], xlab="n", ylab=expression(z), zlab=expression(w),
          colorkey = FALSE, zlim=c(-1,3),
          screen = list(z = 60, x = -60), 
          scales = list( arrows = FALSE, col="black", cex.axis=0.8), 
           aspect = c(1.1, 1),
          drape = TRUE,
          par.settings = list(axis.line = list(col = "transparent")), main="")
```


```{r, FrequencyDensityDependentSelectionFigureS1, echo=FALSE}
pd7<-popdyn7(est7, 25)

ppd7a<-ggplot(pd7, aes(x = year, y = N, color=scenID)) + geom_point(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="A)", x="Year", y = "N")  + 
  theme(axis.title.y = element_text(angle = 0, vjust=0.5)) + geom_line(data=pd7, aes(x = year, y = N2, color=scenID), linetype="dashed",show.legend = FALSE) + geom_line(data=pd7, aes(x = year, y = N3, color=scenID),show.legend = FALSE)

ppd7b<-ggplot(pd7, aes(x = N, y = dndt, color=scenID)) + geom_line(show.legend = FALSE)+ scale_color_manual(values=cols) + theme_classic()  + labs(title="", x="N", y = "dndt")  + theme(axis.title.y = element_text(angle = 0, vjust=0.5))


ggarrange(ppd7a, ppd7b, ncol=2, nrow=1) 
```

```{r, FrequencyDensityDependentSelectionFigureS2, echo=FALSE}

par(mfrow=c(3,3))
hist(ds7a$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds7b$Ind$w, freq=FALSE, xlab="Fitness", main="")
hist(ds7c$Ind$w, freq=FALSE, xlab="Fitness", main="")

hist(ds7a$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds7b$Ind$z, freq=FALSE, xlab="Phenotype", main="")
hist(ds7c$Ind$z, freq=FALSE, xlab="Phenotype", main="")

hist(ds7a$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds7b$Pop$N, freq=FALSE, xlab="Population size", main="")
hist(ds7c$Pop$N, freq=FALSE, xlab="Population size", main="")

```



# Manuscript figures

```{r Figure3, echo=FALSE}

pdf("/home/yi/Dropbox/SocialFitnessEffects/Figures/Fig3.pdf", height= 16, width=12)

ggarrange(p1.n, p1.z, p1.w, p2.n, p2.z, p2.w, p3.n, p3.z, p3.w, p4.n, p4.z, p4.w,ncol=3, nrow=4) 

dev.off()
```

```{r Figure4, echo=FALSE}
pdf("/home/yi/Dropbox/SocialFitnessEffects/Figures/Fig4.pdf", height= 12, width=16)

ggarrange(p5.n, p5.z, p5.w, p6.n, p6.z, p6.w, p7.n, p7.z, p7.w, ncol=3, nrow=3, widths=c(1,1,1)) 

dev.off()
```

```{r Figure5, echo=FALSE}
pdf("Figures/Fig5.pdf", height= 12, width=12)

grid.arrange(p3d1,p3d2,p3d3,p3d4,p3d5,p3d6,p3d7, p3d8, p3d9, ncol=3, nrow=3)

dev.off()

```
